name: CI-CD Pipeline - MLOps

env:
  DOCKER_USER: ${{ secrets.DOCKER_USER }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  REPO_NAME: mlops

# =========================================
# Déclenchement du pipeline
# =========================================
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# =========================================
# Les jobs : CI puis CD
# =========================================
jobs:

  # ---------------------------
  # CI : Vérifications et tests
  # ---------------------------
  ci_pipeline:
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Cloner le dépôt GitHub
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Étape 2 : Installer Python
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # Étape 3 : Installer les dépendances
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f app/requirements.txt ]; then pip install -r app/requirements.txt; fi

      # Étape 4 : Vérification du code (Black & Pylint)
      - name: Code format check (Black)
        run: |
          pip install black
          black --check app/app.py

      - name: Lint (Pylint)
        run: |
          pip install pylint
          pylint --disable=R,C,E0401,W0718 app/app.py

      # Étape 5 : Lancer les tests unitaires
